next_media:
  name: Next media
  description: Load next media from album
  target:
    entity:
      integration: local_photos
      domain: camera
  fields:
    mode:
      name: Mode
      description: Selection of next media
      required: false
      example: "Random"
      default: "Random"
      selector:
        select:
          options:
            - "Random"
            - "Alphabetical order"